ℹ Starting run at 2025-04-08 18:45:54.932783
ℹ Using job id Rt-estimation-2024-11-26T14-38-24-622e8cc8ac3611efbe8d5a0f1d07309c
ℹ Using task id 622e8cc8ac3611efbe8d5a0f1d07309c_CA_COVID-19_1732653504
→ Reading data from './CA_test.parquet'
ℹ Finishing run at 2025-04-08 18:45:54.981381
Warning message:
Pipeline run failed
Caused by error in `check_file_exists()`:
! Cannot read data. File './CA_test.parquet' doesn't exist
Error in `test_path()`:
! Can't find 'tests/testthat'.
Run `rlang::last_trace()` to see where the error occurred.
Error in `test_path()`:
! Can't find 'tests/testthat'.
Run `rlang::last_trace()` to see where the error occurred.
Error in open.connection(con, "rb") : cannot open the connection
In addition: Warning message:
In open.connection(con, "rb") :
  cannot open file './sample_config_with_exclusion.json': No such file or directory
Warning messages:
1: In open.connection(con, "rb") :
  cannot open file './sample_config_with_exclusion.json': No such file or directory
2: Bad config file
Caused by error in `open.connection()`:
! cannot open the connection
ℹ Optional field not in config file: `output_container`
